#!/bin/bash

# KBO 데이터 자동 업데이트 cron 설정 스크립트

echo "🚀 KBO 데이터 자동 업데이트 cron 설정을 시작합니다..."

# 현재 디렉토리 경로
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

echo "📁 프로젝트 경로: $PROJECT_DIR"

# 로그 디렉토리 생성
mkdir -p "$PROJECT_DIR/logs"

# 업데이트 스크립트 생성
cat > "$PROJECT_DIR/auto-update.sh" << 'EOF'
#!/bin/bash

# KBO 데이터 자동 업데이트 실행 스크립트
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$PROJECT_DIR/logs"
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
LOG_FILE="$LOG_DIR/update_$TIMESTAMP.log"

echo "🏏 KBO 데이터 업데이트 시작 - $TIMESTAMP" >> "$LOG_FILE"

cd "$PROJECT_DIR"

# Node.js와 npm이 PATH에 있는지 확인
if ! command -v node &> /dev/null; then
    echo "❌ Node.js를 찾을 수 없습니다. PATH를 확인해주세요." >> "$LOG_FILE"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo "❌ npm을 찾을 수 없습니다. PATH를 확인해주세요." >> "$LOG_FILE"
    exit 1
fi

# 데이터 업데이트 실행
echo "📊 데이터 스크래핑 시작..." >> "$LOG_FILE"
npm run update-data >> "$LOG_FILE" 2>&1

if [ $? -eq 0 ]; then
    echo "✅ 데이터 업데이트 성공!" >> "$LOG_FILE"
    
    # Git 변경사항 확인 및 커밋
    if [ -n "$(git status --porcelain)" ]; then
        git add . >> "$LOG_FILE" 2>&1
        git commit -m "🤖 KBO 데이터 자동 업데이트 - $(date '+%Y-%m-%d %H:%M:%S')

        - 팀 순위 및 성적 업데이트  
        - 매직넘버 재계산
        - 홈/원정 전적 갱신

        🤖 Generated by cron script" >> "$LOG_FILE" 2>&1
        
        git push >> "$LOG_FILE" 2>&1
        
        if [ $? -eq 0 ]; then
            echo "📤 Git 푸시 성공!" >> "$LOG_FILE"
        else
            echo "❌ Git 푸시 실패!" >> "$LOG_FILE"
        fi
    else
        echo "📌 변경사항 없음" >> "$LOG_FILE"
    fi
else
    echo "❌ 데이터 업데이트 실패!" >> "$LOG_FILE"
fi

echo "🏁 업데이트 완료 - $(date '+%Y-%m-%d_%H-%M-%S')" >> "$LOG_FILE"
echo "----------------------------------------" >> "$LOG_FILE"

# 로그 파일 정리 (7일 이상 된 로그 삭제)
find "$LOG_DIR" -name "update_*.log" -mtime +7 -delete
EOF

# 실행 권한 부여
chmod +x "$PROJECT_DIR/auto-update.sh"

echo "✅ 자동 업데이트 스크립트 생성 완료: $PROJECT_DIR/auto-update.sh"

# crontab 백업
if crontab -l > /dev/null 2>&1; then
    crontab -l > "$PROJECT_DIR/crontab_backup.txt"
    echo "📋 기존 crontab 백업 완료: $PROJECT_DIR/crontab_backup.txt"
fi

# 새로운 cron 작업들 생성
cat > "$PROJECT_DIR/kbo_cron_jobs.txt" << EOF
# KBO 데이터 자동 업데이트 (18:00, 22:00, 00:00)
0 18 * * * $PROJECT_DIR/auto-update.sh
0 22 * * * $PROJECT_DIR/auto-update.sh  
0 0 * * * $PROJECT_DIR/auto-update.sh
EOF

echo ""
echo "🕒 cron 작업 설정:"
echo "----------------------------------------"
cat "$PROJECT_DIR/kbo_cron_jobs.txt"
echo "----------------------------------------"
echo ""

# 사용자에게 cron 설정 확인
read -p "❓ 위의 cron 작업들을 설치하시겠습니까? (y/N): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    # 기존 crontab에 새 작업 추가
    (crontab -l 2>/dev/null || true; cat "$PROJECT_DIR/kbo_cron_jobs.txt") | crontab -
    
    if [ $? -eq 0 ]; then
        echo "✅ cron 작업이 성공적으로 설치되었습니다!"
        echo ""
        echo "📋 현재 설정된 cron 작업들:"
        crontab -l
        echo ""
        echo "📁 로그 파일 위치: $PROJECT_DIR/logs/"
        echo "🔧 수동 실행: $PROJECT_DIR/auto-update.sh"
    else
        echo "❌ cron 작업 설치에 실패했습니다."
    fi
else
    echo "ℹ️  cron 작업이 설치되지 않았습니다."
    echo "수동으로 설치하려면 다음 명령어를 실행하세요:"
    echo "crontab -e"
    echo "그리고 다음 내용을 추가하세요:"
    cat "$PROJECT_DIR/kbo_cron_jobs.txt"
fi

echo ""
echo "🎉 설정 완료!"
echo "📖 사용법:"
echo "  - 수동 실행: ./auto-update.sh"
echo "  - 로그 확인: tail -f logs/update_*.log"  
echo "  - cron 확인: crontab -l"
echo "  - cron 제거: crontab -e (수동으로 해당 라인들 삭제)"